/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Categories: () => import('#controllers/categories_controller'),
  FavoriteItems: () => import('#controllers/favorite_items_controller'),
  Folders: () => import('#controllers/folders_controller'),
  InviteAccept: () => import('#controllers/invite_accept_controller'),
  Items: () => import('#controllers/items_controller'),
  ListExport: () => import('#controllers/list_export_controller'),
  ListInvites: () => import('#controllers/list_invites_controller'),
  ListMembers: () => import('#controllers/list_members_controller'),
  Lists: () => import('#controllers/lists_controller'),
  Metas: () => import('#controllers/metas_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PasswordReset: () => import('#controllers/password_reset_controller'),
  PersonalAccessTokens: () => import('#controllers/personal_access_tokens_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Stores: () => import('#controllers/stores_controller'),
}
