/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CategoryTransformer from '#transformers/category_transformer'
import type FavoriteItemTransformer from '#transformers/favorite_item_transformer'
import type FolderTransformer from '#transformers/folder_transformer'
import type ItemTransformer from '#transformers/item_transformer'
import type ListInvitePreviewTransformer from '#transformers/list_invite_preview_transformer'
import type ListInviteTransformer from '#transformers/list_invite_transformer'
import type ListMemberTransformer from '#transformers/list_member_transformer'
import type ListTransformer from '#transformers/list_transformer'
import type MemberCandidateTransformer from '#transformers/member_candidate_transformer'
import type StoreCategoryOrderTransformer from '#transformers/store_category_order_transformer'
import type StoreTransformer from '#transformers/store_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Category = InferData<CategoryTransformer>
  export namespace Category {
    export type Variants = InferVariants<CategoryTransformer>
  }
  export type FavoriteItem = InferData<FavoriteItemTransformer>
  export namespace FavoriteItem {
    export type Variants = InferVariants<FavoriteItemTransformer>
  }
  export type Folder = InferData<FolderTransformer>
  export namespace Folder {
    export type Variants = InferVariants<FolderTransformer>
  }
  export type Item = InferData<ItemTransformer>
  export namespace Item {
    export type Variants = InferVariants<ItemTransformer>
  }
  export type ListInvitePreview = InferData<ListInvitePreviewTransformer>
  export namespace ListInvitePreview {
    export type Variants = InferVariants<ListInvitePreviewTransformer>
  }
  export type ListInvite = InferData<ListInviteTransformer>
  export namespace ListInvite {
    export type Variants = InferVariants<ListInviteTransformer>
  }
  export type ListMember = InferData<ListMemberTransformer>
  export namespace ListMember {
    export type Variants = InferVariants<ListMemberTransformer>
  }
  export type List = InferData<ListTransformer>
  export namespace List {
    export type Variants = InferVariants<ListTransformer>
  }
  export type MemberCandidate = InferData<MemberCandidateTransformer>
  export namespace MemberCandidate {
    export type Variants = InferVariants<MemberCandidateTransformer>
  }
  export type StoreCategoryOrder = InferData<StoreCategoryOrderTransformer>
  export namespace StoreCategoryOrder {
    export type Variants = InferVariants<StoreCategoryOrderTransformer>
  }
  export type Store = InferData<StoreTransformer>
  export namespace Store {
    export type Variants = InferVariants<StoreTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
