import type { HttpContext } from '@adonisjs/core/http'
import type { NextFn } from '@adonisjs/core/types/http'
import { isModernProtocolRequest } from '@jrmc/adonis-mcp/protocols/version'

import crypto from 'node:crypto'

/**
 * MCP protocol middleware generated by @jrmc/adonis-mcp's own configure stub
 * (unchanged except this comment): enforces the Content-Type and — for legacy-era clients
 * (`2025-06-18`/`2025-11-25`, which keep an `initialize`/`MCP-Session-Id` lifecycle) — hands
 * out and echoes session ids. Modern-era (`2026-07-28`, stateless) requests are stateless and
 * carry their protocol metadata on every call, so they pass straight through. Authentication is
 * NOT this middleware's job — see start/routes.ts: the `pat` guard runs after it.
 */
export default class McpMiddleware {
  async handle(ctx: HttpContext, next: NextFn) {
    const body = ctx.request.body()
    const method = body.method

    const contentType = ctx.request.header('Content-Type')?.split(';', 1)[0]
    if (contentType !== 'application/json') {
      return ctx.response.badRequest('Content-Type header must be application/json')
    }

    const headerVersion = ctx.request.header('MCP-Protocol-Version')
    const metadataVersion = body.params?._meta?.['io.modelcontextprotocol/protocolVersion']

    if (isModernProtocolRequest(headerVersion, metadataVersion)) {
      return next()
    }

    if (method === 'initialize') {
      ctx.response.safeHeader('MCP-Session-Id', crypto.randomUUID())
    } else {
      const sessionId = ctx.request.header('MCP-Session-Id')

      if (!sessionId) {
        return ctx.response.badRequest('MCP-Session-Id header is required')
      }

      ctx.response.safeHeader('MCP-Session-Id', sessionId)
    }

    return next()
  }
}
