/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AlexaPreferenceSchema extends BaseModel {
  static $columns = ['createdAt', 'defaultListId', 'id', 'showChecked', 'updatedAt', 'userId'] as const
  $columns = AlexaPreferenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultListId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare showChecked: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BackupSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'frequency', 'id', 'retentionCount', 'timeOfDay', 'updatedAt'] as const
  $columns = BackupSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare frequency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare retentionCount: number
  @column()
  declare timeOfDay: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'forkedFromId', 'icon', 'id', 'isDefault', 'listId', 'name', 'sortOrder', 'updatedAt', 'version'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare forkedFromId: number | null
  @column()
  declare icon: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare listId: number | null
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class CategoryLearningSchema extends BaseModel {
  static $columns = ['categoryId', 'count', 'createdAt', 'id', 'lastSeenAt', 'listId', 'token', 'updatedAt'] as const
  $columns = CategoryLearningSchema.$columns
  @column()
  declare categoryId: number
  @column()
  declare count: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastSeenAt: DateTime
  @column()
  declare listId: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeadlineNotificationSendSchema extends BaseModel {
  static $columns = ['id', 'itemId', 'pushSubscriptionId', 'sentAt'] as const
  $columns = DeadlineNotificationSendSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column()
  declare pushSubscriptionId: number
  @column.dateTime()
  declare sentAt: DateTime
}

export class FavoriteItemSchema extends BaseModel {
  static $columns = ['createdAt', 'defaultCategoryId', 'defaultQuantity', 'deletedAt', 'id', 'listId', 'name', 'notes', 'price', 'storeId', 'updatedAt', 'userId', 'version'] as const
  $columns = FavoriteItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultCategoryId: number | null
  @column()
  declare defaultQuantity: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare listId: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare price: number | null
  @column()
  declare storeId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare version: number
}

export class FolderSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'name', 'sortOrder', 'updatedAt', 'userId', 'version'] as const
  $columns = FolderSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare version: number
}

export class ItemSchema extends BaseModel {
  static $columns = ['categoryId', 'checked', 'checkedAt', 'createdAt', 'createdBy', 'deadline', 'deletedAt', 'id', 'listId', 'name', 'notes', 'price', 'quantity', 'sortOrder', 'storeId', 'updatedAt', 'version'] as const
  $columns = ItemSchema.$columns
  @column()
  declare categoryId: number | null
  @column()
  declare checked: boolean
  @column.dateTime()
  declare checkedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare deadline: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare listId: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare price: number | null
  @column()
  declare quantity: string | null
  @column()
  declare sortOrder: number
  @column()
  declare storeId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class ListInviteSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'expiresAt', 'id', 'listId', 'revokedAt', 'role', 'token', 'updatedAt'] as const
  $columns = ListInviteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare listId: number
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare role: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ListMemberSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'id', 'invitedAt', 'listId', 'role', 'sortOrder', 'updatedAt', 'userId'] as const
  $columns = ListMemberSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare invitedAt: DateTime
  @column()
  declare listId: number
  @column()
  declare role: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ListStoreSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'listId', 'storeId', 'updatedAt'] as const
  $columns = ListStoreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare listId: number
  @column()
  declare storeId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ListSchema extends BaseModel {
  static $columns = ['archived', 'badgeExcluded', 'color', 'createdAt', 'deletedAt', 'folderId', 'icon', 'id', 'insertPosition', 'itemSortOrder', 'maxUncheckedItems', 'name', 'ownerId', 'passcodeHash', 'showPriceInList', 'showStoreInList', 'updatedAt', 'useCategories', 'useCategoryLearning', 'useDeadline', 'useFavorites', 'usePrice', 'useQuantity', 'useRecent', 'useShops', 'version'] as const
  $columns = ListSchema.$columns
  @column()
  declare archived: boolean
  @column()
  declare badgeExcluded: boolean
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare folderId: number | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare insertPosition: string
  @column()
  declare itemSortOrder: string
  @column()
  declare maxUncheckedItems: number | null
  @column()
  declare name: string
  @column()
  declare ownerId: number
  @column()
  declare passcodeHash: string | null
  @column()
  declare showPriceInList: boolean
  @column()
  declare showStoreInList: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare useCategories: boolean
  @column()
  declare useCategoryLearning: boolean
  @column()
  declare useDeadline: boolean
  @column()
  declare useFavorites: boolean
  @column()
  declare usePrice: boolean
  @column()
  declare useQuantity: boolean
  @column()
  declare useRecent: boolean
  @column()
  declare useShops: boolean
  @column()
  declare version: number
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'revokedAt', 'tokenHash', 'updatedAt', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PushSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt', 'vapidPrivateKey', 'vapidPublicKey'] as const
  $columns = PushSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vapidPrivateKey: string
  @column()
  declare vapidPublicKey: string
}

export class PushSubscriptionSchema extends BaseModel {
  static $columns = ['auth', 'createdAt', 'endpoint', 'id', 'p256Dh', 'userId'] as const
  $columns = PushSubscriptionSchema.$columns
  @column()
  declare auth: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endpoint: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare p256Dh: string
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class StoreCategoryOrderSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'deletedAt', 'id', 'sortOrder', 'storeId', 'updatedAt', 'version'] as const
  $columns = StoreCategoryOrderSchema.$columns
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sortOrder: number
  @column()
  declare storeId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class StoreSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'createdBy', 'deletedAt', 'id', 'name', 'updatedAt', 'version'] as const
  $columns = StoreSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class SyncEventSchema extends BaseModel {
  static $columns = ['createdAt', 'entityId', 'entityType', 'id', 'listId', 'occurredAt', 'op', 'payload'] as const
  $columns = SyncEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: number
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare listId: number
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare op: string
  @column()
  declare payload: any | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
