/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'forkedFromId',
    'icon',
    'id',
    'isDefault',
    'listId',
    'name',
    'sortOrder',
    'updatedAt',
    'version',
  ] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare forkedFromId: number | null
  @column()
  declare icon: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare listId: number | null
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class FavoriteItemSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'defaultCategoryId',
    'defaultQuantity',
    'deletedAt',
    'id',
    'listId',
    'name',
    'updatedAt',
    'userId',
    'version',
  ] as const
  $columns = FavoriteItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultCategoryId: number | null
  @column()
  declare defaultQuantity: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare listId: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare version: number
}

export class FolderSchema extends BaseModel {
  static $columns = [
    'color',
    'createdAt',
    'id',
    'name',
    'sortOrder',
    'updatedAt',
    'userId',
    'version',
  ] as const
  $columns = FolderSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare version: number
}

export class ItemSchema extends BaseModel {
  static $columns = [
    'categoryId',
    'checked',
    'checkedAt',
    'createdAt',
    'createdBy',
    'deletedAt',
    'id',
    'listId',
    'name',
    'notes',
    'price',
    'quantity',
    'sortOrder',
    'storeId',
    'updatedAt',
    'version',
  ] as const
  $columns = ItemSchema.$columns
  @column()
  declare categoryId: number | null
  @column()
  declare checked: boolean
  @column.dateTime()
  declare checkedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare listId: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare price: number | null
  @column()
  declare quantity: string | null
  @column()
  declare sortOrder: number
  @column()
  declare storeId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class ListInviteSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'createdBy',
    'expiresAt',
    'id',
    'listId',
    'revokedAt',
    'role',
    'token',
    'updatedAt',
  ] as const
  $columns = ListInviteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare listId: number
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare role: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ListMemberSchema extends BaseModel {
  static $columns = [
    'acceptedAt',
    'createdAt',
    'id',
    'invitedAt',
    'listId',
    'role',
    'updatedAt',
    'userId',
  ] as const
  $columns = ListMemberSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare invitedAt: DateTime
  @column()
  declare listId: number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ListStoreSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'listId', 'storeId', 'updatedAt'] as const
  $columns = ListStoreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare listId: number
  @column()
  declare storeId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ListSchema extends BaseModel {
  static $columns = [
    'archived',
    'badgeExcluded',
    'color',
    'createdAt',
    'deletedAt',
    'folderId',
    'icon',
    'id',
    'name',
    'ownerId',
    'passcodeHash',
    'updatedAt',
    'version',
  ] as const
  $columns = ListSchema.$columns
  @column()
  declare archived: boolean
  @column()
  declare badgeExcluded: boolean
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare folderId: number | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare ownerId: number
  @column()
  declare passcodeHash: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class StoreCategoryOrderSchema extends BaseModel {
  static $columns = [
    'categoryId',
    'createdAt',
    'deletedAt',
    'id',
    'sortOrder',
    'storeId',
    'updatedAt',
    'version',
  ] as const
  $columns = StoreCategoryOrderSchema.$columns
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sortOrder: number
  @column()
  declare storeId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class StoreSchema extends BaseModel {
  static $columns = [
    'color',
    'createdAt',
    'createdBy',
    'deletedAt',
    'id',
    'name',
    'updatedAt',
    'version',
  ] as const
  $columns = StoreSchema.$columns
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class SyncEventSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'entityId',
    'entityType',
    'id',
    'listId',
    'occurredAt',
    'op',
    'payload',
  ] as const
  $columns = SyncEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: number
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare listId: number
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare op: string
  @column()
  declare payload: any | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
